# Generated by Django 5.1.3 on 2024-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_orderdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
