# Generated by Django 5.1.3 on 2024-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_orderdetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='data_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='data_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('OK', 'Принято'), ('COMMENT', 'Оставлен комментарий'), ('NOT OK', 'Не принято')], max_length=10, null=True),
        ),
    ]
