# Generated by Django 5.1.4 on 2024-12-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='uid',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='uid',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
